"""sixth migration

Revision ID: 2710609e427d
Revises: 99b2b854c006
Create Date: 2020-06-07 14:59:59.267673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2710609e427d'
down_revision = '99b2b854c006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_content', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'comment_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('comment_content', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch_content')
    # ### end Alembic commands ###
