"""eighth migration

Revision ID: 9fd7a1d31520
Revises: 71e9d6029e03
Create Date: 2020-06-07 18:36:16.594876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd7a1d31520'
down_revision = '71e9d6029e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitcher_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['pitcher_id'], ['id'])
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'pitcher_id')
    op.drop_column('pitches', 'downvotes')
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
